[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./script" },
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
